FILE_NAME: twitterConfig_threeceeTwitterTest_01.yml
SCREEN_NAME: threecee
CONSUMER_KEY: 5JN3hgxqhqEcxChpKFVmNcLCM
CONSUMER_SECRET: x7zw8brRilR7TSRjaHkm6vHgvhbbbvnymMVQPeZzA6fxWsOBb3
TOKEN: 14607119-3stbyWTHw1Gj2Yln4KBa7h7qWfGOadYr1BYj6qOMP
TOKEN_SECRET: yMquZhEWmhKB02FbrhAMriBYk2B8GHjb21fE3cEhWM6RJ
HIGH_WATER: 0