FILE_NAME: twitterConfig_ninjathreeceeTwitterTest_00.yml
SCREEN_NAME: ninjathreecee
CONSUMER_KEY: JbjtMabzfpLt6UTUYykM21PmE
CONSUMER_SECRET: vwitjm46R9mxSkOll9rk5yL9aYpKqhAq11AW91EcQleK8qH9g3
TOKEN: 1118058524-KKPj6Y5gQUxx3WPWIKtQzoGbj58cMK9I0sZrANL
TOKEN_SECRET: YsG49TkQJopWSTM60CQRlYZKsLdfavFjUnFZ1ixocXTSs
HIGH_WATER: 0