FILE_NAME: twitterConfig_threeceeTwitterTest_02.yml
SCREEN_NAME: threecee
CONSUMER_KEY: rTMijihIEIlwYDSWtPC5cNEq0
CONSUMER_SECRET: PqwdxvkwjhflnfiOMSW7TwugkWqkwE77DLiBKSe5314jfz8L6p
TOKEN: 14607119-sv7mnqzYziulbQNzWufYL4gj4ggNRv30SFEecuwgX
TOKEN_SECRET: UbJaqY8OpL7LUpnOcAxH3mIaDB3uEd4pjcO6dZgLI74UN
HIGH_WATER: 0